apiVersion: v1
kind: Service
metadata:
  name: animation-generator
spec:
  type: NodePort
  selector:
    app: animation-generator
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: animation-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animation-generator
  template:
    metadata:
      labels:
        app: animation-generator
    spec:
      containers:
        - name: animation-generator
          image: {{image}}
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
